In [5]:
2 + 2
a = 2
b = 5
a **3 #8
16 % 5 # probar con otros numeros para entender que significa
2 * a **2 + 0.5 * b + ( a + b ) / 2 # 14

14.0

In [10]:
a = True
b = False
a == b #False
a | b #True
a == ( not b ) #True


True

In [16]:
a , b , c = 3 , 4 , 2 #a = 3, b=4,c=2
a > b #false
a <= b #true
a != b #true
a == b #false
not ( a > b ) #true
(( c > a ) or (10 * c > b ) ) and not ( b / a > c ) #True

(3, 4, 2)

In [19]:
s = [1 , 2 , 3.0 , " hola ", 7 + 3]
s , s [0] , s [1] , s [-1]


([1, 2, 3.0, ' hola ', 10], 1, 2, 10)

In [20]:
import numpy as np
v = np . array ([1 ,2 ,3])
w = np . array ([1.2 , 7 , np . pi ])
v , w , v + w

(array([1, 2, 3]),
 array([1.2       , 7.        , 3.14159265]),
 array([2.2       , 9.        , 6.14159265]))

In [27]:
np . set_printoptions ( precision =2 , suppress = True )
v = np . array ([1 ,2 , np .e ,7])
w = np . array ([1.2 , np . pi , 4 , 5])
for expr in ["v", "w", "v + w", "v ** 2", "v % 2", "np.sum(v)", "np. sqrt (w)", "v > 3", "w < 3.5 "]:
    print ( f"{ expr :11s} == { eval ( expr )}")


v           == [1.   2.   2.72 7.  ]
w           == [1.2  3.14 4.   5.  ]
v + w       == [ 2.2   5.14  6.72 12.  ]
v ** 2      == [ 1.    4.    7.39 49.  ]
v % 2       == [1.   0.   0.72 1.  ]
np.sum(v)   == 12.718281828459045
np. sqrt (w) == [1.1  1.77 2.   2.24]
v > 3       == [False False False  True]
w < 3.5     == [ True  True False False]


In [34]:
( v > 3) | ( w < 3.5)
( v > 3) & ( w < 3.5)

array([False, False, False, False])

In [38]:
~( v > 3) & ~( w < 3.5)

array([False, False,  True, False])

In [40]:
v = np . array ([1 ,2 , np .e ,7]) 
w = np . array ([1.2 , np . pi , 4 , 5])
z = np . array ([0 ,1])
v * w # coord x coord
v +2 # 3, 4, e+2, 9
v + z # Funcionara ? No

array([3.  , 4.  , 4.72, 9.  ])

In [44]:
v = np . array ([1 , 2 , np .e , 7 , 5])
v [0] , v [1] , v [-1] # funcionara ‘v[-2] ‘? || 1, 2, 5. Si, va a dar 7
v [[0 , 3]]
v [0:3] , v [0:1]


(array([1.  , 2.  , 2.72]), array([1.]))

In [47]:
v = np . array ([1 , 2 , np .e , 7 , 5])
w = np . array ([1 , 0 , 2 , 5 , 0])
v [ v > 2] # e , 7, 5
v [ w != 0] # 1, e, 7


array([1.  , 2.72, 7.  ])

In [ ]:
A = np . array ([[3 , 2 , 2] , [-1 , 0 , 1] , [-2 , 2 , 4]])
B = np . array ([[1 , 0 , 0] , [0 , 1 , 0] , [0 , 0 , 1]])
C = np . array ([[0 , 1 , -1] , [5 , -2 , 1]])
A + B
A * B
C **2 # bonus : pruebe con np.